### ISSUE TITLE
See a full example project here return 404 

### ISSUE THREAD

**Issue by behroozbc** [Atlas-LiftTech/MQTTnet.AspNetCore.AttributeRouting#12]
### Describe the bug
hi 
I readme See full example
https://github.com/Atlas-LiftTech/MQTTnet.AspNetCore.AttributeRouting/blob/8e624c1128b754c95014d70a2145ecc9838d97e6/README.md?plain=1#L126
return 404
![image](https://user-images.githubusercontent.com/20381616/137702251-4ba7056a-c98e-4fee-94c6-a7b1d2e990e2.png)

### To Reproduce
open this [link](https://github.com/Atlas-LiftTech/MQTTnet.AspNetCore.AttributeRouting/tree/master/Example) in readme 

### Expected behavior
open example 

### Screenshots
![image](https://user-images.githubusercontent.com/20381616/137702299-2c0025e2-461e-41e3-8590-e1750b7b4d13.png)

**Comment by avishnyak** [comment]
Thanks for the fix.
