### ISSUE TITLE
Upgrade to next version of MqttNet

### ISSUE THREAD

**Issue by mcaden** [Atlas-LiftTech/MQTTnet.AspNetCore.AttributeRouting#21]
### Describe the feature request
This library is no longer compatible with `Mqttnet.AspnetCore` due to drastic breaking changes.

### Describe the solution you'd like
Upgrade to latest version of `Mqttnet.AspnetCore` and `.Net 6`.

**Comment by mcaden** [comment]
Commenting to keep issue open as there's an open PR

**Comment by mcaden** [comment]
Commenting to keep issue open as there's an open PR

**Comment by maikebing** [comment]
Commenting to keep issue open as there's an open PR
