### ISSUE TITLE
Allow unmatched routes/topics to execute

### ISSUE THREAD

**Issue by panoukos41** [Atlas-LiftTech/MQTTnet.AspNetCore.AttributeRouting#6]
### Describe the feature request
The way the library handles routing you have to specify each route yourself, but there are some times that you might not want to do anything with the route so they end up empty and just return an `Ok()` provide an easier way to do this

### Describe the solution you'd like
An overload for `WithAttributeRouting` that accepts a bool and maybe an optional action so that the user could say I want to allow unmatched routes to execute, and then give an action that could perform some logic on it to deem if they want to run it themselves or not.

### Describe alternatives you've considered
Another alternative could be a `magic` keyword on a route that could handle all unmatched routes like `{*unMatched}`

**Comment by avishnyak** [comment]
This sounds good.  Let me think about it and put together an implementation.  I need to research how asp.net core handles this scenario.

**Comment by avishnyak** [comment]
Seems that the .NET AttributeRouting handles it like so:

> You can also apply the [Route] attribute on the controller level, capturing the action as a parameter. That route would then be applied on all actions in the controller, unless a specific [Route] has been defined on a specific action, overriding the default set on the controller.

```sharp
[RoutePrefix(“promotions”)]
[Route(“{action=index}”)]
public class ReviewsController : Controller
{
    // Any route that doesn't match anything else goes to this action
    public ActionResult Index() { … }
 
    // eg.: /promotions/archive
    public ActionResult Archive() { … }
}
```

Source https://devblogs.microsoft.com/aspnet/attribute-routing-in-asp-net-mvc-5/#default-route

**Comment by avishnyak** [comment]
I have added the option to allowUnmatchedRoutes which can be configured like so:

```csharp
// Enable Attribute routing
s.WithAttributeRouting(allowUnmatchedRoutes: true);
```

This will automatically publish any message on a topic that does not match any attribute routes.

In order to add an optional "catch all" handler, simply create a controller inheriting from `MqttBaseController` and add an action to it with a route like this `{*path}`.  This action will catch any routes that are not more specific.

**Comment by panoukos41** [comment]
Awesome and fast, thanks a lot 😄
