### ISSUE TITLE
Can this be used with MQTTNet client?

### ISSUE THREAD

**Issue by lancefi** [Atlas-LiftTech/MQTTnet.AspNetCore.AttributeRouting#8]
I use MQTTnet client to connect to a Mosquito MQTT server.

Can i use this library to setup attribute routing for MQTTnet client? 

I've only managed to figure out how to get it to work with MQTTnet Server.

**Comment by avishnyak** [comment]
Unfortunately not. This library is very similar to ASP.NET WebApi so all the use cases are server-side.
