### ISSUE TITLE
Getting entry assembly question.

### ISSUE THREAD

**Issue by ykarpeev** [Atlas-LiftTech/MQTTnet.AspNetCore.AttributeRouting#9]
I have my solution laid out like this:

- Main Executable
- Class Library with aspnet and controllers.

I realized that AddMqttControllers was getting my main executable assembly here:

` var assemblies = new Assembly[] { Assembly.GetEntryAssembly() };`

Instead of the class library - which caused it not to find any controllers.

I've modified    AddMqttControllers to accept an assembly parameter and then pass the class library assembly in startup like this:

` services.AddMqttControllers(Assembly.GetExecutingAssembly());`

My routes are now discovered.

Is this the suggested solution? Thank you.

https://github.com/Atlas-LiftTech/MQTTnet.AspNetCore.AttributeRouting/blob/7227a32e3b9cef0281e72b06bb2ae257b718ef9a/Source/Extensions/ServiceCollectionExtensions.cs#L26

**Comment by avishnyak** [comment]
In trying to keep this library parallel with ASP.NET itself, I would suggest we add an extension to `.AddApplicationPart()` as documented [here](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-5.0).

See: https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Mvc/Mvc.Core/src/DependencyInjection/MvcCoreMvcBuilderExtensions.cs#L100

**Comment by avishnyak** [comment]
@ykarpeev I have added the ability to pass an array of assemblies to `AddMqttControllers` that should allow you to do what you are attempting to here.

**Comment by ykarpeev** [comment]
Thank you. The new feature is working great for me.
